### ISSUE TITLE
Windows: update.py corrupted čšž in safety_measures.csv

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data#106]
@AuroraBode is using Windows to do daily updates. It seems that there is issue with encoding as `update.py` script on Windows machine corrupts `safety_measures.csv` on export

https://github.com/sledilnik/data/commit/3561eda6e7c9dd03f0a3d333663d704c9c6f03e3

**Comment by overlordtm** [comment]
Fixed in 9b4056ad6bab6c15373bc97469b68fef576fb811
