### ISSUE TITLE
stats.csv: rename cases.active.todate to cases.active

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data#11]
We have now added estimated recovered, closed (recovered+deceased) and active cases.

- `cases.confirmed.todate`
- `cases.recovered.todate` = cases.confirmed.todate(today) - cases.confirmed.todate(-21days)
- `cases.closed.todate` = cases.recovered.todate + state.deceased.todate
- `cases.active` = cases.confirmed.todate - cases.closed.todate

As `cases.active` is is current (today's) state, **we should remove wrong** `.todate` suffix.

Note: as this fields were not used much before, we do not expect any breakage.

**Comment by lukarenko** [comment]
@MihaMarkic, we need to rename it first in REST.

**Comment by mkadunc** [comment]
@lukarenko `cases.closed.todate` je narobe v tekstu zgoraj. Moralo bi bit closed.todate = recovered.todate + deceased.todate
(Predlagam da kar popravis comment.)

Se komentar - invariante za active (ne vem, če kaj pomaga):
```
recovered.todate === recovered.active
deceased.todate === deceased.active
closed.todate === closed.active
closed.todate === recovered.todate + deceased.todate
confirmed.todate === recovered.active + confirmed.active + deceased.active
hospital.active = hospital_regular.active + icu.active
confirmed.active = nonhosp.active + hospital_regular.active + icu.active
```

**Comment by lukarenko** [comment]
Old cases.closed.todate removed
