### ISSUE TITLE
Implement support for OurWorldInData

### ISSUE THREAD

**Issue by breki** [sledilnik/data#36]
The data can be fetched from their Github repository: https://github.com/owid/covid-19-data/tree/master/public/data - it is available both in CSV and JSON formats.

The existing use cases we need covered (@joahim please verify this):

1. Get data for all dates for a specific list of countries.
2. Get data starting from a specific date, for a specific list of countries.
3. Get data starting from a specific date, for all countries.

Countries are specified by their ISO codes.

Data columns we currently need:
- "date"
- "iso_code"
- "new_cases"
- "new_cases_per_million"
- "total_cases"
- "total_cases_per_million"
- "total_deaths"
- "total_deaths_per_million"

The format of the request should be something simple, no need for some kind of a generic query mechanism. I would suggest offering following parameters (whether in query string or input JSON, I don't know):

1. List of country ISO codes. If not specified, data for all countries is returned.
2. Starting and ending dates (both are optional).
3. Output format (requested by @joahim): JSON or CSV.

Also, please leave an option for the null properties in JSON to be skipped (not right now, since our parser currently doesn't support it - I think).

cc: @joahim, @MihaMarkic, @lukarenko, @stefanb

**Comment by joahim** [comment]
@breki Sound good

**Comment by MihaMarkic** [comment]
Yea, yea, I can create my part in data-api.  Output format can be requested through Accept header. I suppose application/json and text/csv are required but we can toss others in as well (i.e. xml if necessary)

**Comment by lukarenko** [comment]
This was done in API
